package com.example.demo.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.model.User;
import com.example.demo.model.UserRequest;
import com.example.demo.model.UserResponse;
import com.example.demo.service.IUserService;
import com.example.demo.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {

    @Autowired
    private IUserService service;

    @Autowired
    private JwtUtil jwtUtil;

    @Autowired
    private AuthenticationManager authenticationManager;

    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user) {
        Integer uid = service.save(user);
        String body = "User " + uid + " saved";
        return new ResponseEntity<String>(body, HttpStatus.CREATED);
    }

    // validate user and generate token (login)
    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request) {
        // validate with username & password with database
        authenticationManager
                .authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
        String token = jwtUtil.generateToken(request.getUsername());
        return ResponseEntity.ok(new UserResponse(token, "Success! Generated By KnowProgram"));
    }
    
    // after login only
    @GetMapping("/welcome")
    public ResponseEntity<String> accessData(Principal p){
        return ResponseEntity.ok("Hello User " + p.getName());
    }

}
