server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: SpringCloudApiGateway

  cloud:
    gateway:
      routes:
        - id: service1-route
          uri: lb://SpringCloudVendorServer   # Load-balanced URI for service1
          predicates:
            - Path=/service1/**               # Matching path for service1
          filters:
            - StripPrefix=1                   # Strips the first prefix from the path

        # Uncomment this block for service2
        # - id: service2-route
        #   uri: lb://SpringCloudVendorServerMicroService2  # Load-balanced URI for service2
        #   predicates:
        #     - Path=/service2/**              # Matching path for service2
        #   filters:
        #     - StripPrefix=1                  # Strips the first prefix from the path
